NIFTY200_SYMBOLS = ["ABB-EQ", "ABCAPITAL-EQ", "ABFRL-EQ", "ACC-EQ",
    "ADANIENT-EQ", "ADANIGREEN-EQ", "ADANIPORTS-EQ",
    "ALKEM-EQ", "AMBUJACEM-EQ", "APOLLOHOSP-EQ",
    "APOLLOTYRE-EQ", "ASHOKLEY-EQ", "ASIANPAINT-EQ",
    "ASTRAL-EQ", 

    
]